package org.AndrePerezGarza.API.Project.delivery.Service;


import org.AndrePerezGarza.API.Project.delivery.DTO.MovieDTO;
import org.AndrePerezGarza.API.Project.delivery.Entity.Movie;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

// This interface implements all the method signatures for the business logic
public interface MovieService {

     // returns all the data in the repository
     List<MovieDTO> findAll();

     // return entries by the autogenerated id
     Optional<Movie> findById(long id);

     // Convert a DTO to an Entity
     MovieDTO save(MovieDTO data);

     // updates the info using an id to search the entry
     void update(long id, MovieDTO data) throws Exception;

     // deletes an entry using the id
     void delete(long id) throws Exception;

     // returns the link based on the input word for the online repository using the MDB API
     String getLink(String name);

     // returns all the movie info based on the input word for the online repository using the MDB API
     String getMovieInfo(String name, String info);


     // returns the link, the name and the year based on the input word from the MDB API
     List<String> findMovie(String name) throws Exception;

     // creates a Movie object and saves it to the repository with all the information based on the input word from the MDB API
     void saveFromName(String name);




}
